packages:
  - "freighter/ts"
  - "client/ts"
  - "console"
  - "my-app"
  - "pluto"
  - "console-electron"
  - "drift"
  - "configs/ts"
  - "configs/eslint"
  - "configs/stylelint"
  - "configs/vite"
  - "docs/site"
  - "x/ts"
  - "x/media"
  - "alamos/ts"
  - "drift/examples/tauri"
  - "landing/"
  - "integration/ts"
