[tool.poetry]
name = "opc"
version = "0.1.0"
description = ""
authors = ["Emiliano Bonilla <56323762+emilbon99@users.noreply.github.com>"]
readme = "README.md"
package-mode = false
[tool.poetry.dependencies]
python = "^3.11"
asyncua = "^1.1.0"
synnax = "^0.14.45"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
