[tool.poetry]
name = "synnax-integration"
version = "0.23.0"
description = ""
authors = ["leo liu <leoliuhy@gmail.com>"]
packages = [
    { include = "./*.py" }
]

[tool.poetry.dependencies]
python = "^3.12"
mypy = "^1.3.0"
pandas = "^2.0.2"
pyTDMS = "^0.0.3"
PyJWT = "^2.5.0"
rich = "^13.4.1"
pick = "^2.0.2"
pydantic = "^1.10.9"
synnax-freighter = { path = "../../freighter/py", develop = true }
alamos = { path = "../../alamos/py", develop = true }
synnax = { path = "../../client/py", develop = true }
click = "^8.1.3"
urllib3 = "^2.0.3"
numpy = "^1.24.3"
matplotlib = "^3.7.1"
nptdms = "^1.7.1"
pytest-asyncio = "^0.21.1"
janus = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^7.3.2"
pytest-asyncio = "^0.21.0"
mypy = "^1.3.0"
pytest-cov = "^4.1.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
