name: "Check API"
on:
  pull_request:
    branches:
      - rc
      - main
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "client/**"
                - "freighter/py/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - "freighter/**"
                - ".github/workflows/test.client.yaml"

  api-typescript:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "client/ts/**"
                - "freighter/ts/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - ".github/workflows/test.client.yaml"

      - name: Setup pnpm
        if: steps.filter.outputs.changed == 'true'
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm install

      - name: Build
        if: steps.filter.outputs.changed == 'true'
        run: pnpm build:client

      - name: Check API
        if: steps.filter.outputs.changed == 'true'
        run: pnpm checkApi:client
