name: "Bump Homebrew Tap"
on:
    push:
        tags:
            - "*"
    workflow_dispatch:
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Update Homebrew formula
              uses: dawidd6/action-homebrew-bump-formula@v3
              with:
                  token: ${{ secrets.HOMEBREW_BUMP_TOKEN }} ## GitHub token (not the default one)
                  tap: synnaxlabs/homebrew-synnax
                  no_fork: true
                  formula: synnax
