name: "Client Test"
on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - ".github/workflows/client.test.yaml"
  workflow_dispatch:
jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
                - "client/py/**"
                - "freighter/py/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - "freighter/**"
                - ".github/workflows/client.test.yaml"

      - name: Set up Python
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        if: steps.filter.outputs.changed == 'true'
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
        working-directory: ./client/py

      - name: Test
        run: pytest --cov=freighter --cov-report xml:coverage.xml
        if: steps.filter.outputs.changed == 'true'
        working-directory: ./client/py

      - name: Upload Coverage
        if: steps.filter.outputs.changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          directory: ./client/py
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: clientpy

    services:
      synnax:
        image: ghcr.io/synnaxlabs/synnax:latest
        env:
          SYNNAX_LISTEN: localhost:9090
          SYNNAX_VERBOSE: true
          SYNNAX_INSECURE: true
          SYNNAX_MEM: true

        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 9090:9090

  test-typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
                - "client/ts/**"
                - "freighter/ts/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - ".github/workflows/client.test.yaml"

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        if: steps.filter.outputs.changed == 'true'
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Test
        if: steps.filter.outputs.changed == 'true'
        run: pnpm cov:client

      - name: Upload Coverage
        if: steps.filter.outputs.changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          directory: ./client/ts
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: clientts

    services:
      synnax:
        image: ghcr.io/synnaxlabs/synnax:latest
        env:
          SYNNAX_LISTEN: localhost:9090
          SYNNAX_VERBOSE: true
          SYNNAX_INSECURE: true
          SYNNAX_MEM: true

        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        ports:
          - 9090:9090
