name: "Console Release"
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  create-release:
#    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - "console/package.json"

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Version
        if: steps.filter.outputs.changed == 'true'
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        working-directory: ./console


      - name: Create Release
        if: steps.filter.outputs.changed == 'true'
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { id } }  = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `console-v${process.env.PACKAGE_VERSION}`,
              name: `Synnax Console v${process.env.PACKAGE_VERSION}`,
              draft: false,
              prerelease: false,
            })
            return id

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - "console/**"
              - "pluto/**"
              - "client/ts/**"
              - "freighter/ts/**"
              - ".github/workflows/console.release.yaml"

      - name: Setup pnpm
        if: steps.filter.outputs.changed == 'true'
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Determine OS
        id: os
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "macos-latest" ]; then
            echo "OS=macos" >> $GITHUB_ENV
          elif [ "${{ matrix.platform }}" = "ubuntu-latest" ]; then
            echo "OS=linux" >> $GITHUB_ENV
          elif [ "${{ matrix.platform }}" = "windows-latest" ]; then
            echo "OS=windows" >> $GITHUB_ENV
          fi

      - name: Get Version
        if: steps.filter.outputs.changed == 'true'
        id: version
        working-directory: ./synnax
        shell: bash
        run: |
          echo "SERVER_VERSION=$(cat pkg/version/VERSION)" >> $GITHUB_ENV


      - name: Install Synnax Binary
        if: steps.filter.outputs.changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = await import("fs");
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const release = releases.data.find(({ tag_name }) => tag_name === `synnax-v${process.env.SERVER_VERSION}`);
            const asset = release.assets.find(({ name }) => name === `synnax-v${process.env.SERVER_VERSION}-${process.env.OS}`);
            const url = asset.browser_download_url;
            const response = await github.request(`GET /repos/${context.repo.owner}/${context.repo.repo}/releases/assets/${asset.id}`, {
              headers: {
                'Accept': 'application/octet-stream',
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            let name;
            const path = "./console/src-tauri/bin";
            if (process.env.OS === "windows") name = `sy-x86_64-pc-windows-msvc.exe`;
            else if (process.env.OS === "macos") name = `sy-x86_64-apple-darwin`;
            else name = `sy-x86_64-unknown-linux-gnu`;
            const buf = Buffer.from(response.data);
            console.log("Pulled Synnax Binary");
            console.log({
                url,
                name,
                version: process.env.SERVER_VERSION,
                path,
            });
            fs.writeFileSync(`${path}/${name}`, buf);
            fs.chmodSync(`${path}/${name}`, 0o755);

      - name: Install Rust Stable
        if: steps.filter.outputs.changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        if: steps.filter.outputs.changed == 'true'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: console/src-tauri -> target
          key: ${{ runner.os }}

      - name: Turbo Cache
        if: steps.filter.outputs.changed == 'true'
        uses: actions/cache@v3
        with:
          path: .turbo-cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies on Ubuntu
        if: matrix.platform == 'ubuntu-latest' && steps.filter.outputs.changed == 'true'
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i


      - name: Build
        if: steps.filter.outputs.changed == 'true'
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: pnpm build:console

      - uses: tauri-apps/tauri-action@v0
        if: steps.filter.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.create-release.outputs.release_id != ''
    needs: [ create-release, build-tauri ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Publish Release
        if: steps.filter.outputs.changed == 'true'
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: process.env.release_id,
                draft: false,
                prerelease: false,
            })

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Get Version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        working-directory: ./console

      - name: Add Auto Update JSON File
        id: auto-update-json-file
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            const fs = await import("fs");

            const packageVersion = process.env.PACKAGE_VERSION;
            const {
              repo: { repo, owner },
            } = context;

            const baseURL = `https://github.com/${owner}/${repo}/releases/download/console-v${packageVersion}/`;

            const darwinURL = baseURL + "Synnax_x64.app.tar.gz";
            const darwinSig = await github.request(`GET ${darwinURL}.sig`);
            const linuxURL = baseURL + `synnax_${packageVersion}_amd64.AppImage.tar.gz`;
            const linuxSig = await github.request(`GET ${linuxURL}.sig`);
            const windowsURL = baseURL + `Synnax_${packageVersion}_x64_en-US.msi.zip`;
            const windowsSig = await github.request(`GET ${windowsURL}.sig`);
            const pub_date = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
            const ecd = new TextDecoder();

            const data = {
              version: `v${packageVersion}`,
              notes: "Synnax Update",
              pub_date,
              platforms: {
                "darwin-x86_64": {
                  signature: ecd.decode(darwinSig.data),
                  url: darwinURL,
                },
                "linux-x86_64": {
                  signature: ecd.decode(linuxSig.data),
                  url: linuxURL,
                },
                "windows-x86_64": {
                  signature: ecd.decode(windowsSig.data),
                  url: windowsURL,
                },
              },
            };

            fs.writeFileSync("console/release-spec.json", JSON.stringify(data, null, 2));

      - name: Commit Auto Update JSON File
        id: commit-auto-update-json-file
        uses: EndBug/add-and-commit@v9
        with:
          add: "*"
          default_author: github_actor
          message: "Auto Update JSON File"
          pull: "--commit --no-edit"
          push: "origin main --force"
