name: "Delta Release"
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

jobs:
  create-release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - "delta/package.json"

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Version
        if: steps.filter.outputs.changed == 'true'
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        working-directory: ./delta

      - name: Create Release
        if: steps.filter.outputs.changed == 'true'
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { id } }  = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `delta-v${process.env.PACKAGE_VERSION}`,
              name: `Synnax Delta v${process.env.PACKAGE_VERSION}`,
              draft: false,
              prerelease: false,
            })
            return id

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - "delta/**"
              - "pluto/**"
              - "client/ts/**"
              - "freighter/ts/**"
              - ".github/workflows/delta.release.yaml"

      - name: Set up pnpm
        if: steps.filter.outputs.changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Rust Stable
        if: steps.filter.outputs.changed == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Rust Cache
        if: steps.filter.outputs.changed == 'true'
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: delta/src-tauri -> target
          key: ${{ runner.os }}

      - name: Turbo Cache
        if: steps.filter.outputs.changed == 'true'
        uses: actions/cache@v3
        with:
          path: .turbo-cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Dependencies on Ubuntu
        if: matrix.platform == 'ubuntu-latest' && steps.filter.outputs.changed == 'true'
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Build
        if: steps.filter.outputs.changed == 'true'
        run: pnpm build:delta

      - uses: tauri-apps/tauri-action@v0
        if: steps.filter.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.create-release.outputs.release_id != ''
    needs: [create-release, build-tauri]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Publish Release
        if: steps.filter.outputs.changed == 'true'
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: process.env.release_id,
                draft: false,
                prerelease: false,
            })

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get Version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        working-directory: ./delta

      - name: Add Auto Update JSON File
        id: auto-update-json-file
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            const fs = await import("fs");

            const packageVersion = process.env.PACKAGE_VERSION;
            const {
              repo: { repo, owner },
            } = context;

            const baseURL = `https://github.com/${owner}/${repo}/releases/download/delta-v${packageVersion}/`;

            const darwinURL = baseURL + "Synnax_x64.app.tar.gz";
            const darwinSig = await github.request(`GET ${darwinURL}.sig`);
            const linuxURL = baseURL + `synnax_${packageVersion}_amd64.AppImage.tar.gz`;
            const linuxSig = await github.request(`GET ${linuxURL}.sig`);
            const windowsURL = baseURL + `Synnax_${packageVersion}_x64_en-US.msi.zip`;
            const windowsSig = await github.request(`GET ${windowsURL}.sig`);
            const pub_date = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
            const ecd = new TextDecoder();

            const data = {
              version: `v${packageVersion}`,
              notes: "Synnax Update",
              pub_date,
              platforms: {
                "darwin-x86_64": {
                  signature: ecd.decode(darwinSig.data),
                  url: darwinURL,
                },
                "linux-x86_64": {
                  signature: ecd.decode(linuxSig.data),
                  url: linuxURL,
                },
                "windows-x86_64": {
                  signature: ecd.decode(windowsSig.data),
                  url: windowsURL,
                },
              },
            };

            fs.writeFileSync("delta/release-spec.json", JSON.stringify(data, null, 2));

      - name: Commit Auto Update JSON File
        id: commit-auto-update-json-file
        uses: EndBug/add-and-commit@v9
        with:
          add: "*"
          default_author: github_actor
          message: "Auto Update JSON File"
          pull: "--commit --no-edit"
          push: "origin main --force"
