name: "Driver Build"
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22000

      - name: Build MbedTLS On Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        shell: bash
        run: |
          curl -LO https://github.com/Mbed-TLS/mbedtls/releases/download/v3.6.0/mbedtls-3.6.0.tar.bz2
          tar -xjf mbedtls-3.6.0.tar.bz2
          mv mbedtls-3.6.0 mbedtls
          cmake -G "Visual Studio 17 2022" -S mbedtls -B mbedtls-build
          cmake --build mbedtls-build --config Release
          cmake --install mbedtls-build --config Release
          cmake --install mbedtls-build --config Release --prefix mbedtls-install
        working-directory: driver/vendor/mbedtls

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.8.1
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Install MbedTLS On Mac
        if: ${{ matrix.platform == 'macos-latest' }}
        run: brew install mbedtls

      - name: Install MbedTLS On Ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
         sudo apt-get install -y libmbedtls-dev
         ls /usr/include/mbedtls
         ls /usr/lib/x86_64-linux-gnu/libmbed*

      - name: Build Open65421 on Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        shell: bash
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL -DCMAKE_INSTALL_PREFIX=../out -DUA_ENABLE_ENCRYPTION=MBEDTLS -DMBEDTLS_LIBRARY="C:\Program Files (x86)\Mbed TLS\lib\mbedtls.lib" -DMBEDX509_LIBRARY="C:\Program Files (x86)\Mbed TLS\lib\mbedx509.lib" -DMBEDCRYPTO_LIBRARY="C:\Program Files (x86)\Mbed TLS\lib\mbedcrypto.lib" -DMBEDTLS_INCLUDE_DIRS="C:\Program Files (x86)\Mbed TLS\include" -DCMAKE_OSX_ARCHITECTURES=x86_64 ..
          cmake --build . --config RelWithDebInfo --target install
        working-directory: driver/vendor/open62541/open62541

      - name: Build Open62541 on Mac and Ubuntu
        if: ${{ matrix.platform == 'macos-latest' || matrix.platform == 'ubuntu-latest' }}
        shell: bash
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUA_NAMESPACE_ZERO=FULL -DCMAKE_INSTALL_PREFIX=../out -DUA_ENABLE_ENCRYPTION=MBEDTLS ..
          cmake --build . --config RelWithDebInfo --target install
        working-directory: driver/vendor/open62541/open62541

      - name: Build Driver on Windows
        if: ${{ matrix.platform == 'windows-latest' }}
        run: bazel --output_user_root=C:/tmp build --enable_platform_specific_config //driver:driver_main --define ni_mock=true

      - name: Build Driver on mac
        if: ${{ matrix.platform == 'macos-latest' }}
        run: bazel build --enable_platform_specific_config //driver:driver_main --define ni_mock=true

      - name: Build Driver on ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: bazel build --enable_platform_specific_config //driver:driver_main --define ni_mock=true
