name: "Pluto Publish"
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'pluto/package.json'
              - '.github/workflows/pluto.publish.yaml'

      - name: Install dependencies
        if: steps.filter.outputs.changed == 'true'
        run: yarn
        working-directory: ./pluto

      - name: Package Lib
        if: steps.filter.outputs.changed == 'true'
        run: yarn build
        working-directory: ./pluto

      - name: Authenticate With Registry
        if: steps.filter.outputs.changed == 'true'
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc
        working-directory: ./pluto

      - name: Publish to Registry
        if: steps.filter.outputs.changed == 'true'
        run: npm publish
        working-directory: ./pluto
