name: Check Versions

on:
  pull_request:
    branches:
      - main
      - rc
  push:
    branches:
      - main
      - rc
      - sy-1375-run-ci-tests-on-windows-and-macos
  workflow_dispatch:

jobs:
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Grant execute permissions for check_version.sh
      run: chmod +x check_version.sh
      working-directory: scripts

    - name: Run version check script
      run: ./check_version.sh
      working-directory: scripts

