name: "Test - Integration"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - leo/sy685-integration-testing
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  test-integration:
    runs-on: self-hosted
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "**/*"

      - name: Test
        run: ./run-integration basic.json
        if: steps.filter.outputs.changed == 'true'
        working-directory: ./integration
