name: "Test - Integration"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - "leo/sy-685-integration-testing"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test-integration-ubuntu:
    runs-on: "Ubuntu"
    timeout-minutes: 1440
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "client/**"
                - "freighter/py/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - "freighter/**"
                - ".github/workflows/test.integration.yaml"

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Build client
        if: steps.filter.outputs.changed == 'true'
        run: pnpm build:client

      - name: Poetry install
        if: steps.filter.outputs.changed == 'true'
        run: poetry install
        working-directory: ./integration/py

      - name: Mini Test
        if: steps.filter.outputs.changed == 'true'
        run: ./run-integration.sh tests/ws-d-r-mini.json
        working-directory: ./integration

      - name: Load test
        if: steps.filter.outputs.changed == 'true'
        run: ./run-integration.sh tests/ws-d-r.json
        working-directory: ./integration

      - name: Benchmark test
        if: steps.filter.outputs.changd == 'true'
        run: ./run-integration.sh tests/benchmark-test.json
        working-directory: ./integration
