name: Test - Computron

on:
  push:
    branches:
      - main
      - rc
  pull_request:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            changed:
              - .github/workflows/test.computron.yaml
              - alamos/go/**
              - computron/**
              - x/go/**

  test:
    name: Test (${{ matrix.os }})
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            format: true
        exclude:
          - os: ${{ github.ref != 'refs/heads/main' && 'macos-latest' }}
          - os: ${{ github.ref != 'refs/heads/main' && 'windows-latest' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Format
        if: matrix.format
        run: scripts/gofmt-check.sh computron

      - name: Install Visual Studio Build Tools
        if: matrix.os == 'windows-latest'
        run: |
          choco install visualstudio2022community -y
          choco install visualstudio2022-workload-vctools -y
          choco install visualstudio2022-workload-nativedesktop -y

      - name: Build Python for Computron
        working-directory: computron
        run: go generate

      - name: Download Dependencies
        working-directory: computron
        run: go mod download

      - name: Move Python DLL (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: computron
        run: |
          Copy-Item python_install\bin\python311.dll .\ -Force

      - name: Run Tests
        working-directory: computron
        run: go test -v -shuffle=on ./...
