name: "Test - Cesium"
on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - sy-1375-run-ci-tests-on-windows-and-macos
  workflow_dispatch:
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - 'alamos/go/**'
              - 'cesium/**'
              - 'x/go/**'
              - '.github/workflows/test.cesium.yaml'

  test:
    name: "Test (${{ matrix.os }})"
    needs: setup
    if: needs.setup.outputs.changed == 'true'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.work"
          cache: "gomod"
          # cache-dependency-path: |
          #   "alamos/go/go.sum"
          #   "cesium/go.sum"
          #   "x/go/go.sum"

      - name: Test
        run: go test -v -shuffle=on ./...
        working-directory: ./cesium
