name: "Test - Integration"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - leo/sy685-integration-testing
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  setup:
    runs-on: self-hosted
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "**/*"

  test-integration:
    needs: [setup]
    runs-on: self-hosted
    if: needs.setup.outputs.changed == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "**/*"

      - name: Set up Python
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        if: steps.filter.outputs.changed == 'true'
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
        working-directory: ./client/py

      - name: Setup Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Test
        run: ./run-integration basic.json
        if: steps.filter.outputs.changed == 'true'
        working-directory: ./integration
