name: "Test - X"
on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - sy-1375-run-ci-tests-on-windows-and-macos
  workflow_dispatch:
jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
      ts: ${{ steps.filter.outputs.ts }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - 'x/go/**'
              - '.github/workflows/test.x.yaml'
            ts:
              - 'x/typescript/**'
              - '.github/workflows/test.x.yaml'

  golang:
    needs: setup
    if: needs.setup.outputs.go == 'true'
    name: "Test: Go (${{ matrix.os }})"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.work"
          cache-dependency-path: |
            "alamos/go/go.sum"
            "x/go/go.sum"

      - name: Test
        run: go test -v -shuffle=on ./...
        working-directory: ./x/go

  typescript:
    name: "Test: TypeScript (${{ matrix.os }})"
    needs: setup
    if: needs.setup.outputs.ts == 'true'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          cache: pnpm
          cache-dependency-path: |
            "pnpm-lock.yaml"

      - name: Test
        run: pnpm test:x
