name: Check Versions
on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
  workflow_dispatch:
jobs:
  check-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Navigate to scripts directory
      run: cd ./scripts

    - name: Grant execute permissions for check_version.sh
      run: chmod +x check_version.sh
      working-directory: ./scripts

    - name: Run version check script
      run: ./check_version.sh
      working-directory: ./scripts

