name: "Test - Synnax"
on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - 'synnax/**'
              - 'cesium/**'
              - 'aspen/**'
              - 'x/**'
              - 'freighter/go/**'
              - '.github/workflows/synnax.test.yaml'

      - name: Set up Go
        uses: actions/setup-go@v5
        if: steps.filter.outputs.changed == 'true'
        with:
          go-version-file: "go.work"
          cache-dependency-path: |
            "alamos/go/go.sum"
            "aspen/go.sum"
            "cesium/go.sum"
            "freighter/go/go.sum"
            "synnax/go.sum"
            "x/go/go.sum"


      - name: Test
        if: steps.filter.outputs.changed == 'true'
        run: go test -tags noui -v ./... --covermode=atomic --coverprofile=coverage.txt --ginkgo.label-filter="!integration && !performance"
        working-directory: ./synnax

      - name: Upload Coverage
        if: steps.filter.outputs.changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          directory: ./synnax
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: synnax
