name: Test - Synnax

on:
  pull_request:
    branches:
      - main
      - rc
  push:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            changed:
              - .github/workflows/test.synnax.yaml
              - alamos/go/**
              - aspen/**
              - cesium/**
              - freighter/go/**
              - synnax/**
              - x/go/**

  test:
    name: Test (${{ matrix.os }})
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            format: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: go.work.sum

      - name: Test
        run: go test -v -shuffle=on ./...
        working-directory: synnax

      - name: Check Formatting
        if: matrix.format
        run: scripts/gofmt-check.sh synnax
