name: "Test - Migration"
on:
  pull_request:
    branches: [rc, main]
  push:
    branches: [rc, main]
  workflow_dispatch:
permissions:
  contents: write
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - "client/**"
              - "freighter/py/**"
              - "synnax/**"
              - "cesium/**"
              - "aspen/**"
              - "x/**"
              - "freighter/**"
              - ".github/workflows/test.client.yaml"

  build-main-server:
    needs: setup
    runs-on: ubuntu-latest
    # if: needs.setup.outputs.changed == 'true'
    env:
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v3
        with:
          ref: main  

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Latest Earthly
        uses: earthly/actions-setup@v1

      - name: Build Main Server Image
        run: earthly --push +docker -tag=main-${GITHUB_SHA} -driver=false
        working-directory: ./synnax

      - name: Push Main Server Image to Github Container Registry
        run: docker push ghcr.io/synnaxlabs/synnax:main-${GITHUB_SHA}

  test-with-main-server:
    needs: build-main-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Main Server
        run: docker run -d --name synnax-main -p 9090:9090 -v /data:/data -e SYNNAX_LISTEN=0.0.0.0:9090 -e SYNNAX_VERBOSE=true -e SYNNAX_INSECURE=true -e SYNNAX_MEM=true -e SYNNAX_LICENSE_KEY=${{ secrets.SYNNAX_LICENSE_KEY }} ghcr.io/synnaxlabs/synnax:main-${GITHUB_SHA}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
        working-directory: ./client/py

      - name: Python Test
        run: pytest --cov=freighter --cov-report xml:coverage.xml
        working-directory: ./client/py
   
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: TS Test
        run: pnpm cov:client

      # - name: Setup Bazel
      #   uses: bazel-contrib/setup-bazel@0.8.1
      #   with:
      #     bazelisk-cache: true
      #     disk-cache: ${{ github.workflow }}
      #     repository-cache: true

      # - name: cpp Test
      #   run: bazel test --test_output=all //client/...

      - name: Stop Main Server
        run: docker stop synnax-main && docker rm synnax-main

  build-current-server:
    needs: test-with-main-server
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Latest Earthly
        uses: earthly/actions-setup@v1

      - name: Build Current Server Image
        run: earthly --push +docker -tag=${GITHUB_SHA} -driver=false
        working-directory: ./synnax

      - name: Push Current Server Image to Github Container Registry
        run: docker push ghcr.io/synnaxlabs/synnax:${GITHUB_SHA}

  test-with-current-server:
    needs: build-current-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Current Server
        run: docker run -d --name synnax-current -p 9090:9090 -v /data:/data -e SYNNAX_LISTEN=0.0.0.0:9090 -e SYNNAX_VERBOSE=true -e SYNNAX_INSECURE=true -e SYNNAX_MEM=true -e SYNNAX_LICENSE_KEY=${{ secrets.SYNNAX_LICENSE_KEY }} ghcr.io/synnaxlabs/synnax:${GITHUB_SHA}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
        working-directory: ./client/py

      - name: Python Test
        run: pytest --cov=freighter --cov-report xml:coverage.xml
        working-directory: ./client/py
   
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: TS Test
        run: pnpm cov:client

      # - name: Setup Bazel
      #   uses: bazel-contrib/setup-bazel@0.8.1
      #   with:
      #     bazelisk-cache: true
      #     disk-cache: ${{ github.workflow }}
      #     repository-cache: true

      # - name: cpp Test
      #   run: bazel test --test_output=all //client/...

      - name: Stop Current Server
        run: docker stop synnax-current && docker rm synnax-current
