name: "Test - Integration"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - "leo/sy-685-integration-testing"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test-integration-windows-benchmark:
    runs-on: "Windows"
    timeout-minutes: 600
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "client/**"
                - "freighter/py/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - "freighter/**"
                - ".github/workflows/test.integration.yaml"

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Build client
        if: steps.filter.outputs.changed == 'true'
        run: pnpm build:client

      - name: Poetry install
        if: steps.filter.outputs.changed == 'true'
        run: poetry install
        working-directory: ./integration/py

      - name: Debug - Print user context
        run: whoami

      - name: Debug - check permissions
        run: Get-Acl -Path ".\"

      - name: TAKEOWN
        run: TAKEOWN /F ~\synnax-data

      - name: Test
        if: steps.filter.outputs.changed == 'true'
        shell: powershell
        run: ./run-integration.ps1 tests/benchmark-test-small.json
        working-directory: ./integration
