name: "Test - Integration"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - "leo/sy-685-integration-testing"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test-integration-ubuntu:
    runs-on: "Ubuntu"
    timeout-minutes: 1440
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "client/**"
                - "freighter/py/**"
                - "synnax/**"
                - "cesium/**"
                - "aspen/**"
                - "x/**"
                - "freighter/**"
                - ".github/workflows/test.integration.yaml"

      - name: Fail on purpose
        run: cd /failfail

      - name: Try run still
        if: ${{ !cancelled() }} && steps.filter.outputs.changed == 'true'
        run: echo "RAN"