name: "Test: Console"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - sy-1375-run-ci-tests-on-windows-and-macos
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - .github/workflows/test.drift.yaml
              - alamos/ts/**
              - client/ts/**
              - configs/eslint/**
              - configs/stylelint/**
              - configs/ts/**
              - configs/vite/**
              - drift/**
              - console/**
              - pluto/**
              - x/media/**
              - x/ts/**

  test:
    name: Test
    needs: setup
    if: needs.setup.outputs.changed == 'true'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            lint: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
          cache-depnendency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build-vite
        working-directory: ./console

      - name: Test
        run: pnpm test:console

      - name: Lint
        if: matrix.lint == true
        run: pnpm lint:console
