name: "Test: Cesium"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - leo-fix-windows-delete
  workflow_dispatch:

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - .github/workflows/test.cesium.yaml
              - alamos/go/**
              - cesium/**
              - x/go/**
  test:
    name: Test (${{ matrix.os }})
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work
          cache-dependency-path: |
            alamos/go/go.sum
            cesium/go.sum
            x/go/go.sum
      - name: Test
        run: go test -v -shuffle=on ./...
        working-directory: cesium
