name: Check Versions

on:
  pull_request:
    branches:
      - main
      - rc
  push:
    branches:
      - main
      - rc
  workflow_dispatch:

jobs:
  check-versions:
    name: Check Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Versions
        run: ./check_version.sh
        working-directory: scripts
