name: "Test - Integration"

on:
  pull_request:
    branches:
      - rc
      - main
  push:
    branches:
      - rc
      - main
      - 'leo/sy-685-integration-testing'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test-integration:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
                - "**/*"

      - name: Install Dependencies
        run: pnpm i

      - name: Build things
        run: pnpm build:client
      
      - name: Install Poetry
        run: |
            pip install poetry
            poetry config virtualenvs.create false
            poetry install
        working-directory: ./client/py

      - name: Poetry install
        run: poetry install
        working-directory: ./integration/py

      - name: Test
        run: ./run-integration.sh basic.json
        working-directory: ./integration
