name: "X Test"
on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - ".github/workflows/x.test.yaml"
  workflow_dispatch:
jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'x/go/**'
              - '.github/workflows/x.test.yaml'

      - name: Set up Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Test
        if: steps.filter.outputs.changed == 'true'
        run: go test -v --covermode=atomic --coverprofile=coverage.txt ./...
        working-directory: ./x/go

      - name: Upload Coverage
        if: steps.filter.outputs.changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          directory: ./x/go
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: gox

  test-typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Diff Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'x/typescript/**'
              - '.github/workflows/x.test.yaml'

      - name: Set up Node
        if: steps.filter.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up pnpm
        if: steps.filter.outputs.changed == 'true'
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        if: steps.filter.outputs.changed == 'true'
        run: pnpm i

      - name: Test
        if: steps.filter.outputs.changed == 'true'
        run: pnpm cov:x

      - name: Upload Coverage
        if: steps.filter.outputs.changed == 'true'
        uses: codecov/codecov-action@v3
        with:
          directory: ./x/ts
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: xts
